### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by Donard97** [Donard97/JavaScript-Capstone-Project#21]
**In this activity, we prepared a Kanban board with a GitHub project.**

## Project requirements

- Copied the Kanban board on our project. ✔️ 
- Created an empty repository for our group project.✔️ 
- Followed the steps described in curriculum-tools-copy-projects.✔️ 
- Opened the GitHub project (Kanban board) in our team repo.✔️ 
- Decided who in our team is Student A or Student B✔️ 
- Assigned ourselves to correct cards ✔️ 

**Here is the link to our project:**

https://github.com/Donard97/JavaScript-Capstone-Project/projects/1

Our team has **2** members ( @Donard97 & @Rustamxon7 ) 👑 👑 

Feel free to review our project. 💪

**Comment by dasileker** [comment]
### **Hi @Donard97 && @Rustamxon7,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- First the submitted PR link is incorrect, you have deletes some part from the link that I sent you via chat see the first screenshot.
- Second the issue itself is incorrect, you should add more details to your issue about the project + the link that supposed to take to the **Project** is incorrect see the first screenshot .
- Third you should assign team member to your project card see the second screenshot.

**First issue**
![fjfjfj](https://user-images.githubusercontent.com/61562626/133106241-f1769b29-dee1-4fb9-9620-e08c369963c9.jpeg)


**Second issue**

![Capture web_13-9-2021_154953_gitlab com](https://user-images.githubusercontent.com/61562626/133106366-b48a85db-77c1-470a-b9aa-0eea8a0f7398.jpeg)


You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
